remote-theme: brummens/workspace-docs

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Workspace Services
# this appears on the top navigation bar next to the home button

site_title: Workspace Services
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Orange Business Services
# this appears in the footer
