remote_theme: brummens/workspace-docs

topnav_title: Workspace Services
# this appears on the top navigation bar next to the home button

site_title: Workspace Services
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Orange Business Services
# this appears in the footer
